
package net.tecgurus.itemservice._1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "itemService", targetNamespace = "http://www.tecgurus.net/itemService/1.0", wsdlLocation = "file:/Users/amaro/WORKSPACE_HOME/TEC_GURUS_JEE_JUL_2/item-project/web/src/main/webapp/wsdl/items.wsdl")
public class ItemService
    extends Service
{

    private final static URL ITEMSERVICE_WSDL_LOCATION;
    private final static WebServiceException ITEMSERVICE_EXCEPTION;
    private final static QName ITEMSERVICE_QNAME = new QName("http://www.tecgurus.net/itemService/1.0", "itemService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/amaro/WORKSPACE_HOME/TEC_GURUS_JEE_JUL_2/item-project/web/src/main/webapp/wsdl/items.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ITEMSERVICE_WSDL_LOCATION = url;
        ITEMSERVICE_EXCEPTION = e;
    }

    public ItemService() {
        super(__getWsdlLocation(), ITEMSERVICE_QNAME);
    }

    public ItemService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ITEMSERVICE_QNAME, features);
    }

    public ItemService(URL wsdlLocation) {
        super(wsdlLocation, ITEMSERVICE_QNAME);
    }

    public ItemService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ITEMSERVICE_QNAME, features);
    }

    public ItemService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ItemService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ItemServicePortType
     */
    @WebEndpoint(name = "itemServicePort")
    public ItemServicePortType getItemServicePort() {
        return super.getPort(new QName("http://www.tecgurus.net/itemService/1.0", "itemServicePort"), ItemServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ItemServicePortType
     */
    @WebEndpoint(name = "itemServicePort")
    public ItemServicePortType getItemServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.tecgurus.net/itemService/1.0", "itemServicePort"), ItemServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ITEMSERVICE_EXCEPTION!= null) {
            throw ITEMSERVICE_EXCEPTION;
        }
        return ITEMSERVICE_WSDL_LOCATION;
    }

}
