
package net.tecgurus.itemservice._1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "itemServicePortType", targetNamespace = "http://www.tecgurus.net/itemService/1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ItemServicePortType {


    /**
     * 
     * @param operacion1Request
     * @return
     *     returns net.tecgurus.itemservice._1.FindStockByIdResponse
     */
    @WebMethod(action = "http://www.tecgurus.net/itemService/itemStockOperation")
    @WebResult(name = "find_stock_by_id_response", targetNamespace = "http://www.tecgurus.net/itemService/1.0", partName = "operacion1_response")
    public FindStockByIdResponse operacionStock(
        @WebParam(name = "find_stock_by_id_request", targetNamespace = "http://www.tecgurus.net/itemService/1.0", partName = "operacion1_request")
        FindStockByIdRequest operacion1Request);

}
